src/Entity/User.php
<?php
	/**
	 * Created by PhpStorm.
	 * User: poiz
	 * Date: 19/03/18
	 * Time: 17:34
	 */
	
	namespace App\Entity;
	
	use App\Helpers\Traits\EntityHelper;
	use Doctrine\Common\Collections\ArrayCollection;
	use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
	use Symfony\Component\Security\Core\Role\RoleHierarchy;
	use Symfony\Component\Security\Core\User\UserInterface;
	use Doctrine\ORM\Mapping as ORM;
	use Symfony\Component\Validator\Constraints as Assert;
	
	
	/**
	 * @ORM\Entity
	 * @ORM\Table(name="user")
	 * @UniqueEntity(fields={"email", "username"}, message="It looks like your
	 *                                already have an account!")
	 */
	class User implements UserInterface {
		use EntityHelper;
		/**
		 * @ORM\Id
		 * @ORM\GeneratedValue(strategy="AUTO")
		 * @ORM\Column(type="integer")
		 */
		private $id;
		
		/**
		 * @Assert\NotBlank()
		 * @Assert\Unique()
		 * @ORM\Column(type="string", name="username", unique=true)
		 */
		private $username = '';
		
		/**
		 * @Assert\NotBlank()
		 * @Assert\Email()
		 * @ORM\Column(type="string", name="email", unique=true)
		 */
		private $email = '';
		
		/**
		 * The encoded password
		 * @var string
		 *
		 * @ORM\Column(type="string", name="password")
		 */
		private $password;
		
		/**
		 * @Assert\NotBlank()
		 * @var string
		 *
		 * @ORM\Column(type="string", name="friendly_name")
		 */
		private $friendly_name = '';
		
		/**
		 * @var int
		 *
		 * @ORM\Column(type="integer", length=5, name="person_id")
		 */
		private $person_id = '';
		
		/**
		 * A non-persisted field that's used to create the encoded password.
		 * @Assert\NotBlank(groups={"Registration"})
		 *
		 * @var string
		 */
		private $plainPassword;
		
		/**
		 * @ORM\Column(type="json_array")
		 */
		private $roles = [];
		
		/**
		 * @var array;
		 */
		private $entityBank = [];
		
		
		/**
		 * @var string
		 */
		private $userNameField = 'username';
		
		// needed by the security system
		public function getUsername() {
			return ( $em = $this->{$this->userNameField} ) ? $em : 'email';
		}
		
		public function getRoles() {
			$roles = $this->roles;
			
			return $roles;
		}
		
		public function setRoles( $roles ) {
			$resRoles = [];
			if ( $roles instanceof ArrayCollection ) {
				foreach ( $roles as $role ) {
					$resRoles[] = $role->getName();
				}
			} else if ( is_array( $roles ) ) {
				foreach ( $roles as $role ) {
					$resRoles[] = $role;
				}
			}
			$this->roles = $resRoles;
		}
		
		public function getPassword() {
			return $this->password;
		}
		
		public function getSalt() {
			// leaving blank - I don't need/have a password!
		}
		
		public function eraseCredentials() {
			$this->plainPassword = null;
		}
		
		public function getEmail() {
			return $this->email;
		}
		
		public function setEmail( $email ) {
			$this->email = $email;
		}
		
		/**
		 * @return string
		 */
		public function getFriendlyName(): string {
			return $this->friendly_name;
		}
		
		/**
		 * @param string $friendly_name
		 */
		public function setFriendlyName( $friendly_name ) {
			$this->friendly_name = $friendly_name;
		}
		
		/**
		 * @return int
		 */
		public function getPersonId() {
			return $this->person_id;
		}
		
		/**
		 * @param int $person_id
		 */
		public function setPersonId( $person_id ) {
			$this->person_id = $person_id;
		}
		
		
		/**
		 * @return string
		 */
		public function getUserNameField() {
			return $this->userNameField;
		}
		
		/**
		 * @param string $userNameField
		 */
		public function setUserNameField( $userNameField ) {
			$this->userNameField = $userNameField;
		}
		
		public function setPassword( $password ) {
			$this->password = $password;
		}
		
		public function getPlainPassword() {
			return $this->plainPassword;
		}
		
		public function setPlainPassword( $plainPassword ) {
			$this->plainPassword = $plainPassword;
			// forces the object to look "dirty" to Doctrine. Avoids
			// Doctrine *not* saving this entity, if only plainPassword changes
			$this->password = null;
		}
		
		public function __toString() {
			return 'User';
		}
		
		
	}

templates/partials/shared/delete-current-item-being-edited.html.twig
{% block top_css_block %}
    <style>
        .pz-delete-item,
        span.fa.fa-trash.pz-delete-item {
            font-size: 1.5em;
            /* color: rgb(95, 0, 143); */
        }
    </style>
{% endblock  %}
{% if clientID %}
    <a class="pz-page-title"
       data-warn-b4-delete="1"
       data-tip="KundenNr. {{ clientID }}<br /><strong style='color:red'>löschen.</strong>"
       data-delete-question="Möchtest Du diesen Kunden mit ID: {{ clientID }} wirklich <strong style='color:red'>löschen?</strong>"
       href="{{ path('rte_admin_delete_client', {'id': clientID}) }}"
       style="display: inline-block;margin-bottom: 15px;font-size: 12px;" >
        <span class="fa fa-trash pz-delete-item"></span> «KundenNr - {{ clientID }}» sofort löschen
    </a>
{% endif %}
{% if ticketID is defined and ticketID %}
    <a class="pz-page-title"
       data-warn-b4-delete="1"
       data-tip="Ticket Nr. {{ ticketID }}<br /><strong style='color:red'>löschen.</strong>"
       data-delete-question="Möchtest Du dieser Ticket Nr. {{ ticketID }} wirklich <strong style='color:red'>löschen?</strong>"
       href="{{ path('rte_admin_delete_ticket', {'id': ticketID}) }}"
       style="display: inline-block;margin-bottom: 15px;font-size: 12px;" >
        <span class="fa fa-trash pz-delete-item"></span> «TicketNr. - {{ ticketID }}» sofort löschen
    </a>
{% endif %}

templates/partials/shared/export.html.twig
{% block top_css_block %}
	<style>
		.pz-export-link{
			display: inline-block;
			min-width: 75px;
			text-align: center;
			box-sizing: border-box;
			padding: 6px 10px;
			margin-right: 5px;
			background: lightgrey;
			border: solid 1px #c1c1c1;
			margin-bottom: 15px;
		}
	</style>
{% endblock %}

{% set pdfURL   = pdfLink is defined and pdfLink ? pdfLink : "?export=pdf" %}
{% set csvURL   = csvLink is defined and csvLink ? csvLink : "?export=csv" %}
{% set jsonURL  = jsonLink is defined and jsonLink ? jsonLink : "?export=json" %}

{% set showPrev     = showPrev      is defined  ? showPrev      : true  %}
{% set showPrint    = showPrint     is defined  ? showPrint     : true  %}
{% set showJSPrint  = showJSPrint   is defined  ? showJSPrint   : false %}
{% set showPDF      = showPDF       is defined  ? showPDF       : false %}
{% set showCSV      = showCSV       is defined  ? showCSV       : false %}
{% set showJSON     = showJSON      is defined  ? showJSON      : false %}

{% if showPrev %}
	<a href="javascript:window.history.back();" class="pz-export-link pz-back-button no-print"><span class="fa fa-chevron-left"></span> Zurück</a>
{% endif %}

{% if showPDF %}
	<a href="{{ pdfURL }}" class="pz-export-link no-print"><span class="fa fa-file-pdf-o"></span> PDF</a>
{% endif %}

{% if showPrint %}
	{# href="javascript:window.print();" #}
	<a  class="pz-export-link pz-print-button no-print"><span class="fa fa-print"></span> Drucken</a>
{% elseif showJSPrint %}
	<a  class="pz-export-link pz-standard-print-button no-print" href="javascript:window.print();"><span class="fa fa-print"></span> Drucken</a>
{% endif %}

{% if showCSV %}
	<a href="{{ csvURL }}" class="pz-export-link no-print"><span class="fa fa-download"></span> CSV</a>
{% endif %}

{% if showJSON %}
	<a href="{{ jsonURL }}" class="pz-export-link no-print"><span class="fa fa-cloud-download"></span> JSON</a>
{% endif %}

templates/partials/shared/filter-table.html.twig
{% block top_css_block%}
    <style>
        .pz-filter-wrapper{
            position:relative;
	        margin-top: 15px;
            width: 100%;
            margin-bottom: -12px;
        }
        input#pz-filter-row-field{
            width: 100%;
            height: 40px;
            border: NONE;
            font-weight: 300;
            letter-spacing: 0.05em;
            font-size: 1.25em;
            color: #48006b;
            border-bottom: solid 1px #b7b7b7;
            border-top: solid 1px #b7b7b7;
            border-radius: 0;
            outline: none;
        }
        .pz-filter-form-group{
            margin-bottom:5px;
            /*
            position: fixed;
            width: 100%;
            margin-bottom: 40px;
            */
        }
        .pz-filter-table-icon{
            position: absolute;
            color: white;
            top: 1px;
            right: 0;
            padding: 12px 13px 12px 13px;
            background: #757575;
            cursor: pointer;
            max-height: 40px;
        }
    </style>
{% endblock %}
<div class="pz-filter-wrapper no-print">
    <div class="form-group pz-filter-table-rows">
        <input type="text"
               id="pz-filter-row-field"
               data-filter-element="{{ filterElement }}"
               data-filter-class="{{ filterCssClass }}"
               data-affected-parent-class="{{ affectedParentClass }}"
               data-affected-parent-tag="{{ affectedParentTag }}"
               class="form-control pz-form-widget"
               placeholder="{{ placeholder }}">
        <span class="fa fa-filter pz-filter-table-icon"></span>
    </div>
</div>

templates/partials/shared/filter.html.twig
{% block top_css_block%}
    <style>
        .pz-filter-wrapper{
            position:relative;
            width: 100%;
        }
        input#pz-filter-field-main{
            width: 100%;
            height: 40px;
            border: NONE;
            font-weight: 300;
            letter-spacing: 0.05em;
            font-size: 1.25em;
            color: #48006b;
            border-bottom: solid 1px #b7b7b7;
            border-top: solid 1px #b7b7b7;
            border-radius: 0;
            outline: none;
        }
        .pz-filter-form-group{
            margin-bottom:5px;
            /*
            position: fixed;
            width: 100%;
            margin-bottom: 40px;
            */
        }
        .pz-filter-icon {
            position: absolute;
            color: white;
            top: 1px;
            right: 0;
            padding: 12px 13px 12px 13px;
            background: #757575;
            cursor: pointer;
            max-height: 40px;
        }
    </style>
{% endblock %}
<div class="pz-filter-wrapper">
    <div class="form-group pz-filter-form-group">
        <input type="text"
               id="pz-filter-field-main"
               data-filter-element="{{ filterElement }}"
               data-filter-class="{{ filterCssClass }}"
               data-affected-parent-class="{{ affectedParentClass }}"
               data-affected-parent-tag="{{ affectedParentTag }}"
               class="form-control pz-form-widget"
               placeholder="{{ placeholder }}">
        <span class="fa fa-filter pz-filter-icon"></span>
    </div>
</div>

templates/partials/shared/logo-box-@header.html.twig
<a href="/"><img style="display:inline-block;width:250px;height:auto;margin-top:20px;"
     src="{{ asset('images/logos/Melanie_JeanRichard_Logo_OK_01.png') }}"
     alt="Melanie JeanRichard Logo"
     class="poiz-logo"
     id="poiz-logo" /></a>

templates/partials/shared/logo-user-header.html.twig
{% block logo_img %}
	<img style="display:inline-block;width:300px;height:auto;margin-top:10px;"
	     src="{{ asset('images/logos/Melanie_JeanRichard_Logo_2020__0.png') }}"
	     alt="Melanie JeanRichard Logo"
	     class="poiz-logo"
	     id="poiz-logo" />
{% endblock %}

{% block top_header_right %}
	<div class="pz-user-status" id="pz-user-status">
		<span class="fa fa-user"></span> Wilkommen, <strong>{{ app.user.friendlyName|ucFirst }}!</strong> &nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="{{ path('app_logout') }}" class="pz-logout-link">
			<span class="fa fa-sign-out"></span> Logout
		</a>
	</div>
{% endblock %}

templates/partials/shared/logout-box-@header.html.twig
{% block top_css_block %}
	<style>
		a.pz-logout-link {
			color: #636363;
			font-weight: 700;
		}
	</style>
{% endblock %}
{% if app.user.friendlyName is defined %}
	{% set appUser = (user is defined) ? user.friendlyName : app.user.friendlyName %}
	<div class="pz-user-status" id="pz-user-status">
		<span class="fa fa-user"></span> {{ greet() }}, <strong>{{ appUser | ucFirst }}!</strong> &nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="{{ path('app_logout') }}" class="pz-logout-link">
			<span class="fa fa-sign-out"></span> Logout
		</a>
	</div>
{% endif %}

templates/partials/shared/scroll-to-top.html.twig
<span class="scroll-to-top no-print" id="scroll-to-top">
    <span class="fa fa-chevron-up scroll-to-top-icon" id="scroll-to-top-icon"></span>
</span>